"""baseline

Revision ID: 7ec4234c579e
Revises: 
Create Date: 2026-09-10 21:20:59.468920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec4234c579e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_investments_category'), 'investments', ['category'], unique=False)
    op.create_index(op.f('ix_sales_category'), 'sales', ['category'], unique=False)
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_payment_status'), 'sales', ['payment_status'], unique=False)
    op.create_foreign_key(None, 'sales', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_payment_status'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_category'), table_name='sales')
    op.drop_index(op.f('ix_investments_category'), table_name='investments')
    # ### end Alembic commands ###
