"""add_pos_multi_item_and_barcode

Revision ID: c9ffcac6e727
Revises: 7ec4234c579e
Create Date: 2026-09-10 21:21:37.846129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ffcac6e727'
down_revision: Union[str, Sequence[str], None] = '7ec4234c579e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sale_id', sa.String(length=36), nullable=False),
    sa.Column('investment_id', sa.String(length=36), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('concepto_tipo', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_usd', sa.Float(), nullable=False),
    sa.Column('unit_cost_ves', sa.Float(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_cost_ves', sa.Float(), nullable=False),
    sa.Column('unit_price_usd', sa.Float(), nullable=False),
    sa.Column('unit_price_ves', sa.Float(), nullable=False),
    sa.Column('total_income_usd', sa.Float(), nullable=False),
    sa.Column('total_income_ves', sa.Float(), nullable=False),
    sa.Column('net_profit_usd', sa.Float(), nullable=False),
    sa.Column('net_profit_ves', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_barcode'), 'sale_items', ['barcode'], unique=False)
    op.create_index(op.f('ix_sale_items_id'), 'sale_items', ['id'], unique=False)
    op.create_index(op.f('ix_sale_items_investment_id'), 'sale_items', ['investment_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    op.add_column('investments', sa.Column('barcode', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_investments_barcode'), 'investments', ['barcode'], unique=False)
    op.add_column('sales', sa.Column('ticket_code', sa.String(length=50), nullable=True))
    op.add_column('sales', sa.Column('subtotal_usd', sa.Float(), nullable=False))
    op.add_column('sales', sa.Column('subtotal_ves', sa.Float(), nullable=False))
    op.add_column('sales', sa.Column('discount_usd', sa.Float(), nullable=False))
    op.add_column('sales', sa.Column('discount_ves', sa.Float(), nullable=False))
    op.create_index(op.f('ix_sales_ticket_code'), 'sales', ['ticket_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_ticket_code'), table_name='sales')
    op.drop_column('sales', 'discount_ves')
    op.drop_column('sales', 'discount_usd')
    op.drop_column('sales', 'subtotal_ves')
    op.drop_column('sales', 'subtotal_usd')
    op.drop_column('sales', 'ticket_code')
    op.drop_index(op.f('ix_investments_barcode'), table_name='investments')
    op.drop_column('investments', 'barcode')
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_investment_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_barcode'), table_name='sale_items')
    op.drop_table('sale_items')
    # ### end Alembic commands ###
